name: CI

on:
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Install git-secrets
        run: |
          git clone https://github.com/awslabs/git-secrets.git
          cd git-secrets
          sudo make install

      - name: Configure git-secrets
        run: |
          git secrets --register-aws

      - name: Run git-secrets scan
        run: |
          git secrets --scan-history

      - run: npm ci

      - name: Build the library
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AVP_ACCESS_ROLE }}
          role-session-name: oidc_federation_vp_authz-clients-js
          aws-region: ${{ vars.AWS_REGION }}
          
      - name: Run unit tests
        run: npm run test
